import { useEffect, useState } from 'react'
import { ArrowRight, BarChart3, Bell, Check, ChevronRight, Clock3, DollarSign, LayoutDashboard, LogOut, Menu, Package, Pencil, Plus, Settings, Store, Utensils, X } from 'lucide-react'
import { formatNaira, restaurants } from './data'

const navigate = (path) => { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')) }
const apiBase = import.meta.env.VITE_API_BASE_URL || 'http://localhost:4000'

const seededOrders = [
  { id: 'DSP-20260917-000001', customer: 'A. Scott', items: 'Smoky party jollof x 1', total: 4305, status: 'PAID', time: '12:42 PM' },
  { id: 'DSP-20260917-000002', customer: 'M. Ojo', items: 'Peppered chicken x 2', total: 9460, status: 'RESTAURANT_ACCEPTED', time: '12:28 PM' },
  { id: 'DSP-20260916-000099', customer: 'T. Efe', items: 'Plantain & egg sauce x 1', total: 3884, status: 'DELIVERED', time: 'Yesterday' },
]

const navItems = [
  ['Overview', '/restaurant/dashboard', LayoutDashboard],
  ['Orders', '/restaurant/orders', Package],
  ['Menu', '/restaurant/menu', Utensils],
  ['Restaurant profile', '/restaurant/profile', Store],
  ['Sales & earnings', '/restaurant/earnings', BarChart3],
]

function PortalShell({ path, children }) {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [user, setUser] = useState(null)
  useEffect(() => { fetch(`${apiBase}/api/auth/me`, { headers: { Authorization: `Bearer ${localStorage.getItem('doorstep-token')}` } }).then((response) => response.ok ? response.json() : null).then((body) => body?.user && setUser(body.user)).catch(() => undefined) }, [])
  const name = user ? `${user.firstName} ${user.lastName}` : 'Restaurant partner'
  return <div className="portal-shell"><aside className={mobileOpen ? 'portal-sidebar is-open' : 'portal-sidebar'}><div className="portal-logo"><span className="brand-mark">✦</span><span>doorstep<span>partner</span></span></div><div className="portal-restaurant"><div className="portal-avatar">{name.charAt(0)}</div><div><strong>{name}</strong><small>Authenticated partner</small></div></div><nav>{navItems.map(([label, href, Icon]) => <button className={path === href ? 'portal-nav active' : 'portal-nav'} key={href} onClick={() => { navigate(href); setMobileOpen(false) }}><Icon size={17} />{label}</button>)}</nav><div className="portal-sidebar-bottom"><button className="portal-nav"><Bell size={17} />Notifications <span className="notification-count">2</span></button><button className="portal-nav"><Settings size={17} />Settings</button><button className="portal-nav" onClick={() => navigate('/')}><LogOut size={17} />Log out</button></div></aside><main className="portal-main"><header className="portal-header"><button className="portal-menu-toggle" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Open partner menu"><Menu size={21} /></button><div><span className="section-kicker">RESTAURANT PARTNER</span><h1>{name}</h1></div><button className="portal-bell" aria-label="Notifications"><Bell size={18} /><b>2</b></button></header>{children}</main></div>
}

function PortalIntro({ eyebrow, title, action }) { return <div className="portal-intro"><div><span className="section-kicker">{eyebrow}</span><h2>{title}</h2></div>{action}</div> }

function Dashboard() {
  return <><PortalIntro eyebrow="TODAY AT A GLANCE" title="Good afternoon, Palm Kitchen." action={<button className="portal-primary" onClick={() => navigate('/restaurant/menu/new')}><Plus size={16} /> Add food</button>} /><div className="demo-banner"><span>DEMO PARTNER WORKSPACE</span><p>Live orders, payouts, and approvals will be API-backed after restaurant authentication is connected.</p></div><section className="metric-grid"><div><span>Orders today</span><strong>18</strong><small>↑ 12% from yesterday</small></div><div><span>Today's sales</span><strong>{formatNaira(68400)}</strong><small>Before commission</small></div><div><span>Average rating</span><strong>4.8 <em>★</em></strong><small>From 126 reviews</small></div><div><span>Acceptance rate</span><strong>94%</strong><small>Last 30 days</small></div></section><section className="portal-columns"><div className="portal-panel"><div className="panel-heading"><div><span className="section-kicker">NEEDS YOUR ATTENTION</span><h3>Incoming orders</h3></div><button onClick={() => navigate('/restaurant/orders')}>View all <ArrowRight size={14} /></button></div>{seededOrders.slice(0, 2).map((order) => <OrderRow order={order} key={order.id} />)}</div><div className="portal-panel quick-actions"><div className="panel-heading"><div><span className="section-kicker">SHORTCUTS</span><h3>Quick actions</h3></div></div><button onClick={() => navigate('/restaurant/menu')}><Utensils size={18} /><span>Manage menu</span><ChevronRight size={15} /></button><button onClick={() => navigate('/restaurant/profile')}><Store size={18} /><span>Update profile</span><ChevronRight size={15} /></button><button onClick={() => navigate('/restaurant/earnings')}><DollarSign size={18} /><span>View earnings</span><ChevronRight size={15} /></button></div></section></>
}

function OrderRow({ order, onStatus }) { const customer = typeof order.customer === 'string' ? order.customer : `${order.customer?.firstName || 'Customer'} ${order.customer?.lastName || ''}`.trim(); const items = Array.isArray(order.items) ? order.items.map((item) => `${item.quantity}× ${item.nameSnapshot}`).join(', ') : order.items; const total = order.total ?? (order.totalMinor ? order.totalMinor / 100 : 0); return <div className="portal-order-row"><div className="order-id"><strong>{order.orderNumber || order.id}</strong><small>{order.time || new Date(order.createdAt).toLocaleString('en-NG')} · {customer}</small></div><div className="order-items">{items}</div><strong>{formatNaira(total)}</strong><span className={`portal-status ${order.status.toLowerCase()}`}>{order.status.replaceAll('_', ' ')}</span>{onStatus && order.status === 'PAID' && <button className="small-action" onClick={() => onStatus(order.id)}>Accept</button>}</div> }

function Orders() {
  const [orders, setOrders] = useState([])
  const token = localStorage.getItem('doorstep-token')
  const load = () => fetch(`${apiBase}/api/restaurant/orders`, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.json()).then((body) => setOrders(body.orders || [])).catch(() => setOrders([]))
  useEffect(() => { load() }, [])
  const accept = async (id) => { const response = await fetch(`${apiBase}/api/orders/${id}/status`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ status: 'RESTAURANT_ACCEPTED' }) }); if (response.ok) load() }
  return <><PortalIntro eyebrow="ORDER MANAGEMENT" title="Orders from your customers." action={<div className="portal-filter"><button className="active">All <b>{orders.length}</b></button><button>New <b>{orders.filter((order) => order.status === 'PAID').length}</b></button><button>Preparing</button><button>Completed</button></div>} /><div className="demo-banner"><span>CONTROLLED WORKFLOW</span><p>Accepting an order advances it from PAID to RESTAURANT_ACCEPTED. Later stages will be server-authorized.</p></div><section className="orders-panel">{orders.map((order) => <OrderRow order={order} onStatus={accept} key={order.id} />)}</section></>
}

function MenuManagement() {
  const [items, setItems] = useState([])
  const [showForm, setShowForm] = useState(false)
  const [editing, setEditing] = useState(null)
  const [draft, setDraft] = useState({ name: '', price: '', description: '' })
  const token = localStorage.getItem('doorstep-token'); const load = () => fetch(`${apiBase}/api/restaurant/menu`, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.json()).then((body) => setItems(body.items || [])); useEffect(() => { load().catch(() => undefined) }, [])
  const addItem = async (event) => { event.preventDefault(); const response = await fetch(`${apiBase}/api/restaurant/menu`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ name: draft.name, description: draft.description, priceMinor: Math.round(Number(draft.price) * 100) }) }); if (response.ok) { setDraft({ name: '', price: '', description: '' }); setShowForm(false); load() } }
  const saveEdit = async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const response = await fetch(`${apiBase}/api/restaurant/menu/${editing.id}`, { method: 'PATCH', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ name: values.name, description: values.description, priceMinor: Math.round(Number(values.price) * 100), available: values.available === 'on' }) }); if (response.ok) { setEditing(null); load() } }
  return <><PortalIntro eyebrow="MENU MANAGEMENT" title="Make your menu easy to choose." action={<button className="portal-primary" onClick={() => setShowForm(!showForm)}>{showForm ? <X size={16} /> : <Plus size={16} />} {showForm ? 'Close' : 'Add food'}</button>} />{showForm && <form className="menu-form" onSubmit={addItem}><div><span className="section-kicker">NEW MENU ITEM</span><h3>Add a food item</h3></div><label>Name<input required value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label>Price in naira<input required type="number" min="0" value={draft.price} onChange={(event) => setDraft({ ...draft, price: event.target.value })} /></label><label>Description<textarea required rows="2" value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label><button className="portal-primary" type="submit"><Check size={16} /> Add to menu</button></form>}{editing && <form className="menu-form" onSubmit={saveEdit}><div><span className="section-kicker">EDIT MENU ITEM</span><h3>{editing.name}</h3></div><label>Name<input required name="name" defaultValue={editing.name} /></label><label>Price in naira<input required name="price" type="number" min="0" defaultValue={editing.priceMinor / 100} /></label><label>Description<textarea required name="description" rows="2" defaultValue={editing.description || ''} /></label><label className="filter-check"><input type="checkbox" name="available" defaultChecked={editing.available} /> Available to customers</label><button className="portal-primary" type="submit"><Check size={16} /> Save item</button></form>}<section className="menu-management-grid">{items.map((item) => <article className="managed-item" key={item.id}><img src={item.imageUrl || restaurants[0].items[0].image} alt="" /><div><span className="portal-status accepted">{item.available ? 'AVAILABLE' : 'HIDDEN'}</span><h3>{item.name}</h3><p>{item.description}</p><strong>{formatNaira(Math.round(item.priceMinor / 100))}</strong></div><button aria-label={`Edit ${item.name}`} onClick={() => setEditing(item)}><Pencil size={15} /></button></article>)}</section></>
}

function Profile() { const [restaurant, setRestaurant] = useState(null); const [message, setMessage] = useState(''); const token = localStorage.getItem('doorstep-token'); useEffect(() => { fetch(`${apiBase}/api/restaurant/profile`, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.json()).then((body) => setRestaurant(body.restaurant)).catch(() => setMessage('Could not load restaurant profile.')) }, []); const save = async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const response = await fetch(`${apiBase}/api/restaurant/profile`, { method: 'PATCH', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(values) }); setMessage(response.ok ? 'Restaurant profile saved.' : 'Could not save restaurant profile.'); if (response.ok) setRestaurant((current) => ({ ...current, ...values })) }; if (!restaurant) return <div className="empty-state">{message || 'Loading restaurant profile...'}</div>; return <><PortalIntro eyebrow="RESTAURANT PROFILE" title="The details customers see." /><form className="profile-form" onSubmit={save}><div className="profile-cover"><img src={restaurants[0].image} alt="Restaurant cover" /><button type="button">Change cover image</button></div><div className="form-row"><label>Restaurant name<input name="name" defaultValue={restaurant.name} /></label><label>Category<input value="Nigerian · Local favourites" readOnly /></label></div><label>Description<textarea name="description" defaultValue={restaurant.description || ''} rows="3" /></label><div className="form-row"><label>Phone number<input name="phone" defaultValue={restaurant.phone || ''} /></label><label>Address<input name="address" defaultValue={restaurant.address} /></label></div>{message && <div className="profile-message">{message}</div>}<button className="portal-primary" type="submit"><Check size={16} /> Save changes</button></form></> }

function Earnings() { const [summary, setSummary] = useState({ orders: [], grossMinor: 0, payoutMinor: 0 }); const token = localStorage.getItem('doorstep-token'); useEffect(() => { fetch(`${apiBase}/api/restaurant/summary`, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.json()).then(setSummary).catch(() => undefined) }, []); const gross = Math.round(summary.grossMinor / 100); const payout = Math.round(summary.payoutMinor / 100); const commission = Math.max(0, gross - payout); return <><PortalIntro eyebrow="SALES & EARNINGS" title="Understand how the kitchen is moving." action={<button className="date-filter"><Clock3 size={15} /> Current records</button>} /><section className="metric-grid"><div><span>Gross sales</span><strong>{formatNaira(gross)}</strong><small>From loaded orders</small></div><div><span>DOORSTEP commission</span><strong>{formatNaira(commission)}</strong><small>Gross less recorded payout</small></div><div><span>Restaurant earnings</span><strong>{formatNaira(payout)}</strong><small>Recorded payout value</small></div><div><span>Orders included</span><strong>{summary.orders.length}</strong><small>Latest 50 orders</small></div></section><section className="portal-panel earnings-note"><BarChart3 size={26} /><div><h3>Financial history will be immutable.</h3><p>Commission percentages and order-item prices are snapshot values on each server-created order.</p></div></section></> }

function OwnerDashboard() { const [summary, setSummary] = useState({ orders: [], grossMinor: 0, payoutMinor: 0 }); const token = localStorage.getItem('doorstep-token'); useEffect(() => { fetch(`${apiBase}/api/restaurant/summary`, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.json()).then(setSummary).catch(() => undefined) }, []); return <><PortalIntro eyebrow="TODAY AT A GLANCE" title="Your kitchen, in motion." action={<button className="portal-primary" onClick={() => navigate('/restaurant/menu/new')}><Plus size={16} /> Add food</button>} /><div className="demo-banner"><span>LIVE PARTNER WORKSPACE</span><p>Your orders, menu, and earnings are connected to DOORSTEP operations.</p></div><section className="metric-grid"><div><span>Orders received</span><strong>{summary.orders.length}</strong><small>Latest 50 orders</small></div><div><span>Gross order value</span><strong>{formatNaira(Math.round(summary.grossMinor / 100))}</strong><small>From loaded orders</small></div><div><span>Restaurant payout value</span><strong>{formatNaira(Math.round(summary.payoutMinor / 100))}</strong><small>Recorded payouts</small></div><div><span>Open orders</span><strong>{summary.orders.filter((order) => !['DELIVERED', 'CANCELLED', 'REFUNDED'].includes(order.status)).length}</strong><small>Need attention</small></div></section><section className="portal-panel orders-panel"><div className="panel-heading"><div><span className="section-kicker">RECENT ORDERS</span><h3>What needs your attention</h3></div><button onClick={() => navigate('/restaurant/orders')}>View all <ArrowRight size={14} /></button></div>{summary.orders.slice(0, 5).map((order) => <OrderRow order={order} key={order.id} />)}{summary.orders.length === 0 && <div className="empty-state">No orders have reached your kitchen yet.</div>}</section></> }

export function RestaurantPortal({ path }) { let content = <OwnerDashboard />; if (path === '/restaurant/orders') content = <Orders />; if (path === '/restaurant/menu' || path === '/restaurant/menu/new') content = <MenuManagement />; if (path === '/restaurant/profile') content = <Profile />; if (path === '/restaurant/earnings') content = <Earnings />; return <PortalShell path={path}>{content}</PortalShell> }
