import { useEffect, useState } from 'react'
import { ArrowRight, Bike, Bell, Check, Clock3, DollarSign, MapPin, Menu, Package, Settings, ShieldCheck, Store, Truck } from 'lucide-react'
import { formatNaira } from './data'

const navigate = (path) => { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')) }
const apiBase = import.meta.env.VITE_API_BASE_URL || 'http://localhost:4000'
const fetch = (input, options) => globalThis.fetch(typeof input === 'string' ? input.replace('http://localhost:4000', apiBase) : input, options)

const riderNav = [['Dashboard', '/rider/dashboard', Truck], ['Available deliveries', '/rider/deliveries', Package], ['Delivery history', '/rider/history', Clock3], ['Earnings', '/rider/earnings', DollarSign], ['Verification', '/rider/verification', ShieldCheck]]
const stages = ['ACCEPTED', 'GOING_TO_RESTAURANT', 'ARRIVED_AT_RESTAURANT', 'PICKED_UP', 'GOING_TO_CUSTOMER', 'DELIVERED']

function RiderShell({ path, children }) {
  const [open, setOpen] = useState(false)
  const [user, setUser] = useState(null)
  useEffect(() => { fetch(`${apiBase}/api/auth/me`, { headers: { Authorization: `Bearer ${localStorage.getItem('doorstep-token')}` } }).then((response) => response.ok ? response.json() : null).then((body) => body?.user && setUser(body.user)).catch(() => undefined) }, [])
  const name = user ? `${user.firstName} ${user.lastName}` : 'Rider'
  return <div className="portal-shell"><aside className={open ? 'portal-sidebar is-open' : 'portal-sidebar'}><div className="portal-logo"><span className="brand-mark">✦</span><span>doorstep<span>rider</span></span></div><div className="portal-restaurant"><div className="portal-avatar">{name.charAt(0)}</div><div><strong>{name}</strong><small>Authenticated rider</small></div></div><nav>{riderNav.map(([label, href, Icon]) => <button className={path === href ? 'portal-nav active' : 'portal-nav'} key={href} onClick={() => { navigate(href); setOpen(false) }}><Icon size={17} />{label}</button>)}</nav><div className="portal-sidebar-bottom"><button className="portal-nav"><Bell size={17} />Notifications <span className="notification-count">1</span></button><button className="portal-nav"><Settings size={17} />Settings</button><button className="portal-nav" onClick={() => navigate('/')}><Truck size={17} />Exit portal</button></div></aside><main className="portal-main"><header className="portal-header"><button className="portal-menu-toggle" onClick={() => setOpen(!open)} aria-label="Open rider menu"><Menu size={21} /></button><div><span className="section-kicker">RIDER PORTAL</span><h1>Good afternoon, {name.split(' ')[0]}.</h1></div><div className="rider-online"><span /> Online</div></header>{children}</main></div>
}

function RiderIntro({ eyebrow, title, action }) { return <div className="portal-intro"><div><span className="section-kicker">{eyebrow}</span><h2>{title}</h2></div>{action}</div> }

function CurrentDelivery({ delivery, setDelivery }) {
  const stage = stages.indexOf(delivery.status)
  const next = stages[stage + 1]
    const advance = async () => { const response = await fetch(`${apiBase}/api/deliveries/by-order/${encodeURIComponent(delivery.order)}/status`, { method: 'POST', headers: { Authorization: `Bearer ${localStorage.getItem('doorstep-token')}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ status: next }) }); if (response.ok) setDelivery({ ...delivery, status: next }) }
  return <section className="rider-delivery-card"><div className="delivery-card-head"><div><span className="section-kicker">ACTIVE DELIVERY</span><h3>{delivery.order}</h3></div><span className="portal-status accepted">{delivery.status.replaceAll('_', ' ')}</span></div><div className="delivery-route"><div><Store size={17} /><span><small>Pickup</small><strong>{delivery.restaurant}</strong><em>{delivery.pickup}</em></span></div><div className="route-line" /><div><MapPin size={17} /><span><small>Drop-off</small><strong>{delivery.customer}</strong><em>{delivery.dropoff}</em></span></div></div>{next ? <button className="portal-primary" onClick={advance}>{next === 'DELIVERED' ? <Check size={16} /> : <ArrowRight size={16} />} {next.replaceAll('_', ' ')}</button> : <div className="delivered-label"><Check size={17} /> Delivery completed</div>}</section>
}

function RiderDashboard() { const [online, setOnline] = useState(false); const [delivery, setDelivery] = useState(null); const token = localStorage.getItem('doorstep-token'); useEffect(() => { fetch('http://localhost:4000/api/rider/deliveries', { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.json()).then((body) => { const active = body.deliveries?.find((item) => item.riderId); if (active) setDelivery({ order: active.order.orderNumber, restaurant: active.order.restaurant.name, pickup: active.order.restaurant.address, customer: 'Customer', dropoff: active.order.addressSnapshot, status: active.status }) }).catch(() => undefined) }, []); const toggleOnline = async () => { const next = online ? 'OFFLINE' : 'ONLINE'; const response = await fetch('http://localhost:4000/api/rider/availability', { method: 'PATCH', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ availability: next }) }); if (response.ok) setOnline(!online) }; return <><RiderIntro eyebrow="TODAY AT A GLANCE" title="Ready for the next good trip?" action={<button className={online ? 'online-toggle active' : 'online-toggle'} onClick={toggleOnline}><span /> {online ? 'Online' : 'Offline'}</button>} /><div className="demo-banner"><span>LIVE RIDER WORKSPACE</span><p>Your availability and assigned deliveries are now synchronized with DOORSTEP operations.</p></div><section className="metric-grid"><div><span>Today's deliveries</span><strong>7</strong><small>2 still active</small></div><div><span>Today's earnings</span><strong>{formatNaira(9800)}</strong><small>Before payout</small></div><div><span>Acceptance rate</span><strong>88%</strong><small>Last 30 days</small></div><div><span>Your rating</span><strong>4.9 <em>★</em></strong><small>From 84 deliveries</small></div></section><section className="rider-layout">{delivery ? <CurrentDelivery delivery={delivery} setDelivery={setDelivery} /> : <div className="rider-delivery-card"><span className="section-kicker">NO ACTIVE DELIVERY</span><h3>Ready when an assignment arrives.</h3><p>Go online to receive available delivery requests.</p></div>}<div className="portal-panel"><div className="panel-heading"><div><span className="section-kicker">DELIVERY CARE</span><h3>Before you move</h3></div></div><div className="rider-care"><Bike size={20} /><p>Only share your location while an active delivery is in progress. Customer and restaurant details stay limited to the current order.</p></div><button className="text-link" onClick={() => navigate('/rider/verification')}>View verification <ArrowRight size={14} /></button></div></section></> }

function Available() { const [deliveries, setDeliveries] = useState([]); const token = localStorage.getItem('doorstep-token'); useEffect(() => { fetch(`${apiBase}/api/rider/deliveries`, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.json()).then((body) => setDeliveries(body.deliveries || [])).catch(() => undefined) }, []); const claim = async (id) => { const response = await fetch(`${apiBase}/api/deliveries/${id}/claim`, { method: 'POST', headers: { Authorization: `Bearer ${token}` } }); if (response.ok) navigate('/rider/dashboard') }; return <><RiderIntro eyebrow="AVAILABLE DELIVERIES" title="Choose your next route." /><section className="orders-panel">{deliveries.filter((delivery) => delivery.status === 'AVAILABLE').map((delivery) => <div className="portal-order-row" key={delivery.id}><div className="order-id"><strong>{delivery.order.orderNumber}</strong><small>{delivery.order.restaurant.name}</small></div><div className="order-items">{delivery.order.restaurant.address} → {delivery.order.addressSnapshot}</div><strong>{formatNaira(delivery.order.deliveryFeeMinor / 100)}</strong><button className="small-action" onClick={() => claim(delivery.id)}>Accept</button></div>)}{deliveries.length === 0 && <div className="empty-state">No delivery requests are available right now.</div>}</section></> }

function History() { const [orders, setOrders] = useState([]); const token = localStorage.getItem('doorstep-token'); useEffect(() => { fetch(`${apiBase}/api/rider/history`, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.json()).then((body) => setOrders(body.orders || [])).catch(() => undefined) }, []); return <><RiderIntro eyebrow="DELIVERY HISTORY" title="Every trip, accounted for." /><section className="orders-panel">{orders.map((order) => <div className="portal-order-row" key={order.id}><div className="order-id"><strong>{order.orderNumber}</strong><small>{new Date(order.createdAt).toLocaleDateString('en-NG')} · {order.restaurant?.name}</small></div><div className="order-items">Completed delivery</div><strong>{formatNaira(Math.round((order.riderPayout?.amountMinor || 0) / 100))}</strong><span className="portal-status delivered">{order.status}</span></div>)}{orders.length === 0 && <div className="empty-state">No rider history is available yet.</div>}</section></> }

function Earnings() { const [totalMinor, setTotalMinor] = useState(0); const [payouts, setPayouts] = useState([]); const token = localStorage.getItem('doorstep-token'); useEffect(() => { fetch(`${apiBase}/api/rider/earnings`, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.json()).then((body) => { setTotalMinor(body.totalMinor || 0); setPayouts(body.payouts || []) }).catch(() => undefined) }, []); return <><RiderIntro eyebrow="RIDER EARNINGS" title="Know what every delivery earns." /><section className="metric-grid"><div><span>Completed deliveries</span><strong>{payouts.length}</strong><small>Recorded deliveries</small></div><div><span>Delivery earnings</span><strong>{formatNaira(Math.round(totalMinor / 100))}</strong><small>Recorded payout value</small></div><div><span>Paid out</span><strong>{formatNaira(Math.round(payouts.filter((payout) => payout.status === 'PAID').reduce((sum, payout) => sum + payout.amountMinor, 0) / 100))}</strong><small>Completed payouts</small></div><div><span>Pending payout</span><strong>{formatNaira(Math.round(payouts.filter((payout) => payout.status !== 'PAID').reduce((sum, payout) => sum + payout.amountMinor, 0) / 100))}</strong><small>Awaiting processing</small></div></section><section className="portal-panel earnings-note"><DollarSign size={26} /><div><h3>Server-owned earnings</h3><p>Your payout history is calculated from completed delivery records and cannot be changed from the browser.</p></div></section></> }

function Verification() { return <><RiderIntro eyebrow="VERIFICATION" title="Keep your rider record ready." /><section className="portal-panel verification-panel"><ShieldCheck size={23} /><div><h3>Verification is operations-controlled</h3><p>Identity, vehicle, and safety documents are reviewed privately by DOORSTEP operations before delivery access is enabled.</p></div></section></> }

export function RiderPortal({ path }) { let content = <RiderDashboard />; if (path === '/rider/deliveries') content = <Available />; if (path === '/rider/history') content = <History />; if (path === '/rider/earnings') content = <Earnings />; if (path === '/rider/verification') content = <Verification />; return <RiderShell path={path}>{content}</RiderShell> }
