export const publicRoutes = [
  '/',
  '/restaurants',
  '/food',
  '/offers',
  '/how-it-works',
  '/track-order',
  '/help',
  '/login',
  '/forgot-password',
  '/register',
  '/partners/restaurants',
  '/partners/restaurants/register',
  '/partners/restaurants/login',
  '/riders',
  '/riders/register',
  '/riders/login',
  '/cart',
  '/checkout',
  '/payment/callback',
  '/account/orders',
  '/account/profile',
  '/account/addresses',
  '/account/favorites',
  '/account/notifications',
  '/account/support',
  '/location',
  '/privacy',
  '/terms',
  '/refund-policy',
  '/cancellation-policy',
  '/restaurant-partner-terms',
  '/rider-terms',
  '/delivery-policy',
  '/contact',
]

export const futureRoutes = {
  customer: ['/account/reviews', '/payment/success', '/payment/failed', '/payment/pending'],
  restaurant: ['/restaurant/dashboard', '/restaurant/orders', '/restaurant/menu', '/restaurant/profile', '/restaurant/earnings'],
  rider: ['/rider/dashboard', '/rider/deliveries', '/rider/history', '/rider/earnings', '/rider/profile'],
  admin: ['/admin/login', '/admin/dashboard', '/admin/customers', '/admin/restaurants', '/admin/riders', '/admin/orders', '/admin/live', '/admin/payments', '/admin/commissions', '/admin/settings', '/admin/audit-logs'],
}
